# Generated automatically
services:
  tor-0:
    container_name: tor-0
    image: dockage/tor-privoxy:latest
    ports:
      - "25000:8118"
    environment:
      - IP_CHANGE_SECONDS=60
    restart: always
  tor-1:
    container_name: tor-1
    image: dockage/tor-privoxy:latest
    ports:
      - "25001:8118"
    environment:
      - IP_CHANGE_SECONDS=60
    restart: always
  tor-2:
    container_name: tor-2
    image: dockage/tor-privoxy:latest
    ports:
      - "25002:8118"
    environment:
      - IP_CHANGE_SECONDS=60
    restart: always

  proxy-gateway:
    image: haproxy:latest
    container_name: tor-gateway
    ports:
      - "8080:8080"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    restart: always
